# Generated by Django 5.2.8 on 2025-12-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='alt')),
                ('title_fa', models.CharField(max_length=24, null=True, verbose_name='alt')),
                ('title_en', models.CharField(max_length=24, null=True, verbose_name='alt')),
                ('photo', models.ImageField(upload_to='gallery/', verbose_name='عکس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'توضیحات درباره ما',
                'verbose_name_plural': 'توضیحات درباره ما',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='نام')),
                ('title_fa', models.CharField(max_length=24, null=True, verbose_name='نام')),
                ('title_en', models.CharField(max_length=24, null=True, verbose_name='نام')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='عکس')),
                ('rule', models.CharField(max_length=24, verbose_name='شغل')),
                ('rule_fa', models.CharField(max_length=24, null=True, verbose_name='شغل')),
                ('rule_en', models.CharField(max_length=24, null=True, verbose_name='شغل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ما',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='alt')),
                ('photo', models.ImageField(upload_to='gallery/', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ما',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Honer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=36, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=36, null=True, verbose_name='عنوان')),
                ('award', models.CharField(max_length=36, verbose_name='جایزه')),
                ('award_fa', models.CharField(max_length=36, null=True, verbose_name='جایزه')),
                ('award_en', models.CharField(max_length=36, null=True, verbose_name='جایزه')),
                ('year', models.CharField(max_length=12, verbose_name='سال')),
                ('year_fa', models.CharField(max_length=12, null=True, verbose_name='سال')),
                ('year_en', models.CharField(max_length=12, null=True, verbose_name='سال')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'افتخارات',
                'verbose_name_plural': 'افتخارات ما',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=48, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=48, null=True, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات ما',
                'ordering': ('id',),
            },
        ),
    ]
