# Generated by Django 5.2.8 on 2025-11-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='نام سایت')),
                ('title_fa', models.CharField(max_length=128, null=True, verbose_name='نام سایت')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='نام سایت')),
                ('since', models.CharField(max_length=24, verbose_name='تاریخ')),
                ('description', models.TextField(verbose_name='توضیحات اولیه سایت')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات اولیه سایت')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات اولیه سایت')),
                ('photo', models.ImageField(upload_to='logo/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
        ),
    ]
