# Generated by Django 5.2.8 on 2025-11-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='نام شرکت')),
                ('photo', models.ImageField(upload_to='client/', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(verbose_name='لینک تلگرام')),
                ('instagram', models.URLField(verbose_name='لینک اینستاگرام')),
                ('whatsapp', models.URLField(verbose_name='لینک واتس اپ')),
                ('office_phone', models.CharField(max_length=18, verbose_name='شماره دفتر')),
                ('phone', models.CharField(max_length=18, verbose_name='شماره شخصی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'اطلاعات فوتر',
                'verbose_name_plural': 'اطلاعات فوتر',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='نام')),
                ('title_fa', models.CharField(max_length=128, null=True, verbose_name='نام')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='نام')),
                ('since', models.CharField(max_length=24, verbose_name='تاریخ تولد')),
                ('since_fa', models.CharField(max_length=24, null=True, verbose_name='تاریخ تولد')),
                ('since_en', models.CharField(max_length=24, null=True, verbose_name='تاریخ تولد')),
                ('photo', models.ImageField(upload_to='manager/', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'مدیریت',
                'verbose_name_plural': 'مدیریت',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=48, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=48, null=True, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('description_fa', models.TextField(null=True, verbose_name='توضیحات')),
                ('description_en', models.TextField(null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'چرا ما',
                'verbose_name_plural': 'چرا ما',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='firstcontent',
            options={'ordering': ('id',), 'verbose_name': 'نام سایت', 'verbose_name_plural': 'نام سایت'},
        ),
    ]
