# Generated by Django 5.2.8 on 2025-11-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_client_footer_manager_whyus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='icon',
            field=models.CharField(default=1, max_length=128, verbose_name='آیکون'),
            preserve_default=False,
        ),
    ]
