# Generated by Django 5.2.8 on 2025-11-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='نام دسته')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='نام دسته')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان محصول')),
                ('title_fa', models.CharField(max_length=150, null=True, verbose_name='عنوان محصول')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='عنوان محصول')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('short_description_fa', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Product.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('-created_at',),
            },
        ),
    ]
